sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t ivorontsova/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ivorontsova/docker-react npm run test